#comment out this profile and change password if you want to create local postgresql db
spring.profiles.active: dev

---
spring.profiles: dev
spring.flyway.enabled: false

---
spring.profiles: stage
spring.flyway.enabled: false
spring.datasource.password: postgres
spring.datasource.username: postgres
spring.datasource.url: jdbc:postgresql://192.168.56.111:5432/postgres
spring.datasource.driver-class-name: org.postgresql.Driver